### PR TITLE
Enhancement/refactor exceptions [FIXES #32]

### LINKED ISSUE #32: Refactoring
There are couple of things that are slowly diverting from a proper path that probably need to be addressed now.

- **Exceptions** Currently the exceptions are thrown everywhere without any structure, It would be better if the exceptions are grouped and structured in a way that allows for their extension and usage(e.g. assigning error handling functions/codes)

- **Tests** Our tests are currently not coherent. As we have recently moved to in-memory db testing this should be easier to reason about. We need to
    1. Have a common package for all utils, mocks, stubs, spies, etc...
    2. Have a common standard (e.g. common lifecycle)
    3. populating the db with data for the test case is currently tedious and repetitive. this should be easily fixed if we do i & ii.
    4. Run the unit tests function wise

### PR DESCRIPTION
**Pull request by osopromadze**
fixes #32 

Moved all exceptions into the same package. They are extended from BaseException class. Created messages.properties in resources/i18n folder, and exceptions get error messages from that file. Created global exception handler class and there is constructing final output error object with status code, timestamp and message.

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Hello @osopromadze, thank you very much for this PR! It looks great at a first glance. We will review it in the next few days and give an answer at the beginning of next week.

**Comment by osopromadze** [comment]
Great @chaoran-chen, thanks for letting me know 👍

**Comment by chaoran-chen** [comment]
Hi. Would it be possible to remove projectlombok from the dependencies since we are also not using it in the other classes? But the library is very nice and maybe we will introduce it consistently for the whole project at a later point in time.

File: src/main/java/science/icebreaker/account/AccountService.java [hunk 1]
```diff
@@ -132,7 +137,7 @@ public int createAccount(RegistrationRequest registration) throws AccountCreatio
      */
     public String login(Account account) {
         if (account.getId() != null) {
-            throw new IllegalArgumentException("The account id is not null.");
+            throw new AccountCreationException().withErrorCode(ErrorCodeEnum.ERR_ACC_002);
```
Comment (dajenet) [inline src/main/java/science/icebreaker/account/AccountService.java]: This has nothing to do with account creation. So maybe better use a IllegalArgumentException or IllegalRequestParameterException.

File: src/main/java/science/icebreaker/exception/AppExceptionHandler.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+    @ExceptionHandler({
+            AccountCreationException.class,
+            AccountNotFoundException.class,
+            InvalidFiltersException.class,
+            DeviceAvailabilityCreationException.class,
+            IllegalRequestParameterException.class
+    })
+    public ResponseEntity<Object> handleAccountCreationException(HttpServletRequest request, BaseException exception, Locale locale) {
```
Comment (dajenet) [inline src/main/java/science/icebreaker/exception/AppExceptionHandler.java]: Because you are handling different exceptions here it would be better to choose a more general method name.

**Review by dajenet — COMMENTED** [review]
Hi @osopromadze, thank you for your PR. It looks good. I just added a few comments.

File: src/main/java/science/icebreaker/exception/AppExceptionHandler.java (hunk 2 above)
Comment (osopromadze) [reply src/main/java/science/icebreaker/exception/AppExceptionHandler.java]: @dajenet good idea choosing more general name, or handle different type of exceptions in different methods, but as method body is same thats why I put them in same. Feel free to change it as you consider.

**Comment by osopromadze** [comment]
> Hi. Would it be possible to remove projectlombok from the dependencies since we are also not using it in the other classes? But the library is very nice and maybe we will introduce it consistently for the whole project at a later point in time.

Yes, no problem, Just added project lombok to easily generate constructros, or getters and setters. Can be removed easily and write code without it.

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
The import in `src/test/java/science/icebreaker/device_availability/DeviceAvailabilityServiceTest.java#20` needs to be adapted since the `DeviceAvailabilityCreationException` was moved. And for consistency, `DeviceAvailabilityNotFoundException` should also be moved to the `science.icebreaker.exception` package.

**Comment by osopromadze** [comment]
> The import in `src/test/java/science/icebreaker/device_availability/DeviceAvailabilityServiceTest.java#20` needs to be adapted since the `DeviceAvailabilityCreationException` was moved. And for consistency, `DeviceAvailabilityNotFoundException` should also be moved to the `science.icebreaker.exception` package.

@chaoran-chen done. All tests passed and moved `DeviceAvailabilityNotFoundException` in exception package.

**Review by chaoran-chen — APPROVED** [review]
Great. Thank you!
